{% set version = "0.4.6" %}

package:
  name: pymwm
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --use-feature=in-tree-build . -vv"

requirements:
  host:
    - pip
    - python
    - numpy
    - scipy
    - cython
    - setuptools
  run:
    - python
    - riip
    - matplotlib
    - numpy
    - scipy
    - pandas
    - ipython

test:
  imports:
    - pymwm

about:
  home: "https://github.com/mnishida/PyMWM"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python 3 + Pandas wrapper for the refractiveindex.info database"
  doc_url: https://github.com/mnishida/RII_Pandas/tree/master/tutorial

extra:
  recipe-maintainers:
    - mnishida
