{% set version = "0.5.7" %}

package:
  name: pymwm
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - numpy
    - scipy
    - cython
    - setuptools
  run:
    - python
    - riip
    - matplotlib
    - numpy
    - scipy
    - pandas
    - ipython

test:
  imports:
    - pymwm

about:
  home: "https://github.com/mnishida/PyMWM"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Metallic waveguide mode solver written in Python"
  doc_url: https://github.com/mnishida/PyMWM/blob/master/docs/notebooks/00_tutorial.ipynb

extra:
  recipe-maintainers:
    - mnishida
