#!/usr/bin/env python
# -*- coding: utf-8 -*-
import numpy as np
import pymwm
params = {'core': {'shape': 'cylinder', 'size': 0.2,
                   'fill': {'model': 'air'}},
          'clad': {'model': 'gold_dl'},
          'bounds': {'lmax': 1.2, 'lmin': 0.545, 'limag': 10.0},
          'modes': {'num_n': 6, 'num_m': 2}}
wg = pymwm.create(params)
w = 2 * np.pi / 1.2
alpha = ('M', 0, 1)
print(alpha)
wg.plot_e_field(w, 'h', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'h', alpha, 'x', 0.3)
wg.plot_e_field_on_x_axis(w, 'h', alpha, 'z', 0.3)
wg.plot_h_field(w, 'h', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'h', alpha, 'y', 0.3)
alpha = ('M', 0, 2)
print(alpha)
wg.plot_e_field(w, 'h', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'h', alpha, 'x', 0.3)
wg.plot_e_field_on_x_axis(w, 'h', alpha, 'z', 0.3)
wg.plot_h_field(w, 'h', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'h', alpha, 'y', 0.3)
alpha = ('M', 1, 1)
print(alpha)
wg.plot_e_field(w, 'h', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'h', alpha, 'x', 0.3)
wg.plot_e_field_on_x_axis(w, 'h', alpha, 'z', 0.3)
wg.plot_h_field(w, 'h', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'h', alpha, 'y', 0.3)
alpha = ('M', 2, 1)
print(alpha)
wg.plot_e_field(w, 'h', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'h', alpha, 'x', 0.3)
wg.plot_e_field_on_x_axis(w, 'h', alpha, 'z', 0.3)
wg.plot_h_field(w, 'h', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'h', alpha, 'y', 0.3)
alpha = ('E', 0, 1)
print(alpha)
wg.plot_e_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'v', alpha, 'y', 0.3)
wg.plot_h_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'x', 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'z', 0.3)
alpha = ('E', 1, 1)
print(alpha)
wg.plot_e_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'v', alpha, 'y', 0.3)
wg.plot_h_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'x', 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'z', 0.3)
alpha = ('E', 1, 2)
print(alpha)
wg.plot_e_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'v', alpha, 'y', 0.3)
wg.plot_h_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'x', 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'z', 0.3)
alpha = ('E', 2, 1)
print(alpha)
wg.plot_e_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'v', alpha, 'y', 0.3)
wg.plot_h_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'x', 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'z', 0.3)
alpha = ('E', 3, 1)
print(alpha)
wg.plot_e_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_e_field_on_x_axis(w, 'v', alpha, 'y', 0.3)
wg.plot_h_field(w, 'v', alpha, 0.3, 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'x', 0.3)
wg.plot_h_field_on_x_axis(w, 'v', alpha, 'z', 0.3)
